### ISSUE TITLE
Slf4jIllegalPassedClass check: NoSuchMethodError: MethodMatchers$MethodNameMatcher.withParameters()

### ISSUE THREAD

**Issue by remal** [KengoTODA/errorprone-slf4j#153]
I'm getting this error after updating errorprone-slf4j to 0.1.6:

`java.lang.NoSuchMethodError: 'com.google.errorprone.matchers.method.MethodMatchers$ParameterMatcher com.google.errorprone.matchers.method.MethodMatchers$MethodNameMatcher.withParameters(java.lang.String, java.lang.String[])'`

<details>
<summary>Click here to view full log</summary>

```
     BugPattern: Slf4jIllegalPassedClass
     Stack Trace:
     java.lang.NoSuchMethodError: 'com.google.errorprone.matchers.method.MethodMatchers$ParameterMatcher com.google.errorprone.matchers.method.MethodMatchers$MethodNameMatcher.withParameters(java.lang.String, java.lang.String[])'
  	at jp.skypencil.errorprone.slf4j.IllegalPassedClass$LoggerInitializerVisitor.<init>(IllegalPassedClass.java:114)
  	at jp.skypencil.errorprone.slf4j.IllegalPassedClass$LoggerInitializerVisitor.<init>(IllegalPassedClass.java:96)
  	at jp.skypencil.errorprone.slf4j.IllegalPassedClass.matchMethodInvocation(IllegalPassedClass.java:43)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:223)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:885)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:974)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at ...
```
</details>

**ErrorProne version: 2.10.0**
**Java version: 11**

Is there a chance that errorprone-slf4j 0.1.6 requires ErrorProne 2.11?

**Comment by KengoTODA** [comment]
memo: according to https://github.com/google/error-prone/issues/2909#issuecomment-1021966080 this fix should be fixed by #137 but we still have a usage: 

https://github.com/KengoTODA/errorprone-slf4j/blob/bb79cd77052ae06d1415b4fe882692db41785523/src/main/java/jp/skypencil/errorprone/slf4j/IllegalPassedClass.java#L114

**Comment by KengoTODA** [comment]
Ah, I understand. 

> ErrorProne version: 2.10.0

You should use 2.11 instead, because Errorprone apply [an breaking change to their API](https://github.com/google/error-prone/commit/ccb01275000f26edc260f606e42d7528a692a5b7#).

**Comment by KengoTODA** [comment]
Updated the release note to tell this problem to other users:
https://github.com/KengoTODA/errorprone-slf4j/releases/tag/v0.1.6

I'll try to introduce code to check Errorprone version on the fly.

**Comment by remal** [comment]
I supposed that this issue is connected to ErrorProne 2.11, thanks for the confirmation!

However, we can't
upgrade ErrorProne at the moment, as we faced another issue with 2.11: https://github.com/mockito/mockito/issues/2554 :disappointed:. We'll be waiting to get all the issues fixed and then upgrade errorprone-slf4j.
